[UserSettings]
DATA_DIR = "./data"
SAVE_GAME_TO_FILE = false
SAVE_FILE = "./data/savefile.txt"
LOG_OUTPUT = "stderr"
LOG_LEVEL = "Logging.Warn"
PRINT_BOARD = false
MAX_TURNS = 500

[GameSettings]
[PlayerSettings]
MODEL = "./src/learning/model20250407.jls"
FEATURES = "./data/features.csv"
STATE_VALUES = "./data/state_values.csv"
[PlayerSettings.blue]
[PlayerSettings.cyan]
[PlayerSettings.green]
[PlayerSettings.yellow]
