SAVE_MAP = ""
WRITE_FEATURES = false
TEAMS = ["blue", "cyan", "green", "yellow"]

[Tournament]
GAMES_PER_MAP = 100
MAPS_PER_EPOCH = 2
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[Async]
CHANNELS = ["main", "public"]
[Async.main]
SIZE = 32
[Async.public]
SIZE = 32

[HypothGameSettings]
LOG_OUTPUT = "stderr"
LOG_LEVEL = "Warn"

[GameSettings]
[PlayerSettings]
MODELS_DIR = "../CatanLearning.jl/models"
MODELS = ["decision", "public"]
MODEL = "./models/model.jls"
PUBLIC_MODEL = "./models/public_model.jls"
FEATURES = "./data/features.csv"
STATE_VALUES = "./data/state_values.csv"
SEARCH_DEPTH = 2
[PlayerSettings.blue]
[PlayerSettings.cyan]
[PlayerSettings.green]
[PlayerSettings.yellow]
[PlayerSettings.decision]
FILE = "model.jls"
[PlayerSettings.public]
FILE = "public_model.jls"
