SAVE_GAME_TO_FILE = false
SAVE_FILE = "./data/savefile.txt"
LOG_OUTPUT = "./log_debug.txt"
LOG_LEVEL = "Logging.Debug"
PRINT_BOARD = true
MAX_TURNS = 500

[Tournament]
GAMES_PER_MAP = 100
MAPS_PER_EPOCH = 2
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[GameSettings]
[PlayerSettings]
MODEL = "./models/model.jls"
PUBLIC_MODEL = "./models/public_model.jls"
FEATURES = "./data/features.csv"
STATE_VALUES = "./data/state_values.csv"
SEARCH_DEPTH = 2
[PlayerSettings.blue]
[PlayerSettings.cyan]
[PlayerSettings.green]
[PlayerSettings.yellow]
