SAVE_MAP = ""
WRITE_FEATURES = false
# Check if the features files header matches the runtime feature set
FEATURE_SANITY_CHECK = true

[Tournament]
GAMES_PER_MAP = 100
MAPS_PER_EPOCH = 2
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[Async]
CHANNELS = ["main", "public"]
[Async.main]
SIZE = 32
[Async.public]
SIZE = 32



[GameSettings]
[PlayerSettings]
MODEL = "./models/model.jls"
PUBLIC_MODEL = "./models/public_model.jls"
FEATURES = "./data/features.csv"
STATE_VALUES = "./data/state_values.csv"
SEARCH_DEPTH = 2
[PlayerSettings.blue]
[PlayerSettings.cyan]
[PlayerSettings.green]
[PlayerSettings.yellow]
